# Generated by Django 3.2.7 on 2021-09-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinelearning', '0005_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
