# Generated by Django 3.2.7 on 2021-09-07 05:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_surname', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.IntegerField()),
                ('customer_email', models.EmailField(max_length=200)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('account', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
