# Generated by Django 3.2.7 on 2021-09-07 14:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_type', models.CharField(max_length=200)),
                ('account_balance', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.customer', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=25)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=25)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=25)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=25)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=25)),
                ('amount_of_transcation', models.DecimalField(decimal_places=2, max_digits=25)),
                ('transaction_description', models.CharField(max_length=500)),
                ('account', models.ManyToManyField(blank=True, to='projects.Checking')),
            ],
        ),
        migrations.CreateModel(
            name='Savings_Withdrawals',
            fields=[
                ('savings_withdrawn_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount_withdrawn', models.DecimalField(decimal_places=2, max_digits=25)),
                ('date_withdrawn', models.DateField(auto_now_add=True)),
                ('time_withdrawn', models.TimeField(auto_now_add=True)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=25)),
                ('account', models.ManyToManyField(blank=True, to='projects.Savings')),
            ],
        ),
        migrations.CreateModel(
            name='Savings_Deposits',
            fields=[
                ('savings_deposits_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount_deposited', models.DecimalField(decimal_places=2, max_digits=25)),
                ('date_deposited', models.DateField(auto_now_add=True)),
                ('time_deposited', models.TimeField(auto_now_add=True)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=25)),
                ('account', models.ManyToManyField(blank=True, to='projects.Savings')),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount_loaned', models.DecimalField(decimal_places=2, max_digits=25)),
                ('date_loaned', models.DateField(auto_now_add=True)),
                ('amount_standing', models.DecimalField(decimal_places=2, max_digits=25)),
                ('due_date', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Checking_Withdrawals',
            fields=[
                ('checking_withdrawals_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_withdrawn', models.DecimalField(decimal_places=2, max_digits=25)),
                ('date_withdrawn', models.DateField(auto_now_add=True)),
                ('time_withdrawn', models.TimeField(auto_now_add=True)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=25)),
                ('account', models.ManyToManyField(blank=True, to='projects.Checking')),
            ],
        ),
        migrations.CreateModel(
            name='Checking_Deposits',
            fields=[
                ('checking_deposits_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_deposited', models.DecimalField(decimal_places=2, max_digits=25)),
                ('date_deposited', models.DateField(auto_now_add=True)),
                ('time_deposited', models.TimeField(auto_now_add=True)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=25)),
                ('account', models.ManyToManyField(blank=True, to='projects.Checking')),
            ],
        ),
    ]
