# Generated by Django 3.2.7 on 2021-09-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_customer_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='featured_image',
            field=models.ImageField(blank=True, default='defaultt.jpg', null=True, upload_to=''),
        ),
    ]
