# Generated by Django 3.2.7 on 2021-09-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machinelearning', '0001_initial'),
        ('projects', '0007_alter_customer_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machinelearning.profile'),
        ),
    ]
